import React, { useEffect } from "react";
import Head from "next/head";
import Link from "next/link";
import useIdleTimer from "../src/hooks/useIdleTimer";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { handleOnIdle, handleOnActive, resetTotalActiveTime } = useIdleTimer(
    "readTextbook",
    1134
  );

  useEffect(() => {
    handleOnActive();

    return () => {
      handleOnIdle();
      resetTotalActiveTime();
    };
  }, [handleOnActive, handleOnIdle, resetTotalActiveTime]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet
          ipsam accusamus dolore quo hic voluptate natus, eaque provident sit
          voluptas perspiciatis ipsum quidem soluta quaerat commodi nihil
          magnam, non atque similique temporibus fugiat exercitationem numquam
          neque! Excepturi maxime veritatis quia officiis voluptate provident
          dignissimos optio veniam itaque dolore, odio in voluptas voluptatibus
          dicta harum odit aliquam beatae praesentium fugiat possimus ratione
          quas nulla dolorum ab! Ducimus repellendus rerum voluptas velit
          inventore quas impedit, dicta voluptatem ipsum non architecto ratione
          est quae magnam consequuntur minus aliquid provident beatae similique,
          quo maiores repellat at adipisci? Cumque iste magni dolore amet vero
          at architecto laborum et ducimus. Dignissimos perferendis debitis
          facilis. Recusandae, voluptatem itaque neque nulla quia consectetur
          perspiciatis inventore accusamus nihil minus impedit beatae quidem
          excepturi rem repellat doloremque hic, blanditiis aliquid. Dolorem
          veniam ullam quod voluptas vel amet rem eum, dolorum nam dolore labore
          culpa distinctio laudantium nemo autem mollitia soluta.
        </p>

        <Link href="/">
          <a className={styles.link}>
            <button>К имитации автопроверок</button>
          </a>
        </Link>
      </main>
    </div>
  );
}
