import React, { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import useIdleTimer from "../src/hooks/useIdleTimer";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [timerIsActive, setTimerIsActive] = useState(false);
  const { startTimer, stopTimerAndRequestTimeToBackend } = useIdleTimer(
    "solveAutocheckTask",
    "html-100"
  );

  useEffect(() => {
    return () => {
      if (timerIsActive) {
        stopTimerAndRequestTimeToBackend();
      }
    };
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <button
            onClick={async () => {
              await setTimerIsActive(true);
              await startTimer();
            }}
          >
            Start time activity
          </button>
          <button
            onClick={async () => {
              await setTimerIsActive(false);
              await stopTimerAndRequestTimeToBackend();
            }}
          >
            End time activity
          </button>
        </div>

        <Link href="/conspectus">
          <a className={styles.link}>
            <button>К конспектам</button>
          </a>
        </Link>
      </main>
    </div>
  );
}
